<?php

namespace SultanovSolutions\LaravelBase;

use SultanovSolutions\LaravelBase\Providers\BaseServiceProvider;

class SSBaseServiceProvider extends BaseServiceProvider
{
    public function boot()
    {
        parent::boot();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
